apiVersion: v1 
kind: ConfigMap 
metadata:
  name: example-configmap 
data:
  #Configuration values can be set as key-value properties
  MESSAGE: KARTHIK KARTHIK KARTHIK-Hello from example-configmap


